name: Setup Erlang Examples

on:
  push:
    branches:
      - master

jobs:
  # otp-release-rebar3:
  #   strategy:
  #     matrix:
  #       platforms: [ubuntu, macos, windows]
  #       version: [25, 26, 27]
  #   runs-on: ${{ matrix.platforms }}-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: erlangsters/setup-erlang@v1
  #     with:
  #       erlang-version: ${{ matrix.version }}
  #       install-rebar3: true
  #   - run: cd otp-release-rebar3 && rebar3 as prod release

  # otp-release-erlang-mk:
  #   strategy:
  #     matrix:
  #       platforms: [ubuntu, macos, windows]
  #       version: [25, 26, 27]
  #   runs-on: ${{ matrix.platforms }}-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: erlangsters/setup-erlang@v1
  #     with:
  #       erlang-version: ${{ matrix.version }}
  #   - run: cd otp-release-erlang-mk && make rel

  # nif-library-rebar3:
  #   strategy:
  #     matrix:
  #       platforms: [ubuntu, macos, windows]
  #       version: [25] # [25, 26, 27]
  #   runs-on: ${{ matrix.platforms }}-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: erlangsters/setup-erlang@v1
  #     with:
  #       erlang-version: ${{ matrix.version }}
  #       install-rebar3: true
  #   - run: |
  #       cd nif-library-rebar3
  #       rebar3 compile
  #       rebar3 eunit

  nif-library-erlang-mk:
    strategy:
      matrix:
        platforms: [windows] # [ubuntu, macos, windows]
        version: [25] # [25, 26, 27]
    runs-on: ${{ matrix.platforms }}-latest
    steps:
    - uses: actions/checkout@v4
    - uses: erlangsters/setup-erlang@v1.0.1
      id: setup-erlang
      with:
        erlang-version: ${{ matrix.version }}
    - run: |
        ls ${{ steps.setup-erlang.outputs.erlang-location }}
        ls ${{ steps.setup-erlang.outputs.erlang-location }}/bin

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: false
        install: >-
          git
          make
          mingw-w64-x86_64-gcc
        path-type: inherit

    - run: |
        ls ${{ steps.setup-erlang.outputs.erlang-location }}
        ls ${{ steps.setup-erlang.outputs.erlang-location }}/bin

    - shell: msys2 {0}
      run: |
        cd nif-library-erlang-mk
        make